{% set name = "psy-maps" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data.get('version') }}

source:
  path: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('CONDA_PY') }}_{{ environ.get('GIT_BUILD_STR', '') }}{% if environ.get('GIT_BRANCH') %}_{{ environ.get('GIT_BRANCH').replace('-', '') }}{% endif %}{% if environ.get("BUILD_STR_END") %}_{{ environ.get("BUILD_STR_END") }}{% endif %}
  script: python -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - psy-simple
    - cartopy

test:
  imports:
    - psy_maps
    - psy_maps.plotters

  requires:
    - pytest
    - pytest-cov
    - codecov
    - dask
    - pyqt
    - xarray
    - netCDF4
    - seaborn
  source_files:
    - tests
  commands:
    - pytest -sv --cov=psy_maps --ref
    - py.test -sv --cov-append --cov=psy_maps

about:
  home: https://github.com/Chilipp/psy-maps
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Psyplot plugin for visualization on a map

  description: |
    This psyplot plugin uses the cartopy package to visualize geo-referenced
    data on a map
  doc_url: http://psyplot.readthedocs.io/projects/psy-maps
  dev_url: https://github.com/Chilipp/psy-maps
